stages:
  - .pre
  - lint
  - build
  - test
  - .post
variables:
  NODE_VERSION: '18'
prettier:
  stage: lint
  image:
    name: node:${NODE_VERSION}
  before_script:
    - npm install -g prettier
  script:
    - npx prettier --write "**/*.{js,jsx,ts,tsx,json,css,scss,md}" --check
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  artifacts:
    reports:
      junit: prettier-report.xml
    expire_in: 1 week
lint-frontend:
  stage: lint
  image:
    name: node:${NODE_VERSION}
  script:
    - cd packages/frontend
    - npm ci
    - npm run lint
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
lint-backend:
  stage: lint
  image:
    name: node:${NODE_VERSION}
  script:
    - cd packages/backend
    - npm ci
    - npm run lint
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
lint-engine:
  stage: lint
  image:
    name: node:${NODE_VERSION}
  script:
    - cd packages/engine
    - npm ci
    - npm run lint
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
build-frontend:
  stage: build
  image:
    name: node:${NODE_VERSION}
  script:
    - cd packages/frontend
    - npm ci
    - npm run build
  artifacts:
    paths:
      - packages/frontend/dist
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
build-backend:
  stage: build
  image:
    name: node:${NODE_VERSION}
  script:
    - cd packages/backend
    - npm ci
    - npm run build
  artifacts:
    paths:
      - packages/backend/dist
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
build-engine:
  stage: build
  image:
    name: node:${NODE_VERSION}
  script:
    - cd packages/engine
    - npm ci
    - npm run build
  artifacts:
    paths:
      - packages/engine/dist
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
default: {}
